CREATE DATABASE ProjectManagement;
CREATE USER rajeev WITH PASSWORD 'admin';
GRANT ALL PRIVILEGES ON DATABASE ProjectManagement TO rajeev;

ALTER USER rajeev WITH CREATEDB;

GRANT USAGE, CREATE ON SCHEMA public TO rajeev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rajeev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO rajeev;
ALTER DEFAULT PRIVILEGES FOR USER rajeev IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO rajeev;
ALTER DEFAULT PRIVILEGES FOR USER rajeev IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO rajeev;
